---
- name: Qtree server Setup
  become: yes
  hosts: all
  tasks:
    - name: Create an application user
      user:
        name: qtree
        password: test1234
    - name: Create application file
      file:
        path: /root/sample.html
        state: touch    