---
- name: Qtree server Setup
  become: yes
  hosts: servergroup
  tasks:
    - name: Create an application user
      user:
        name: qtree12
        password: test323
    - name: Create application file
      file:
        path: /root/ajeesh.html
        state: touch    
