---
- name: Qtree server Setup
  become: yes
  hosts: servergroup
  tasks:
    - name: Create an application user
      user:
        name: qtree54
        password: test55123
    - name: Create application file
      file:
        path: /root/Test123.html
        state: touch    
